import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {harness,master} from './harness.mjs';
const url='https://miqueas80.github.io/NEXUS-X-voice-v2-test/';
test('Voice V2: claves y eventos de producción se conservan y no se leen',async()=>{
 const seeds={'nexus_xkiro_api_key_v1':'test-placeholder','nexus_x_favorites_v1':'["production-only"]','nexus_x_voice_language_v1':'production-only'};const source=fs.readFileSync(new URL('./app.js',import.meta.url),'utf8').replace("'use strict';","'use strict';for(const [key,value]of Object.entries("+JSON.stringify(seeds)+"))globalThis.localStorage.setItem(key,value);");const h=harness({url,source,stored:master.records.slice(0,1)});try{await h.api.loadMaster();assert.equal(h.api.state.inventory.length,111);assert.equal(h.api.state.favorites.size,0);h.api.saveInventory();assert.equal(JSON.parse(h.window.localStorage.getItem('nexus_x_inventory_v1')).length,1);assert.equal(JSON.parse(h.window.localStorage.getItem('nexus-voice-v2-test:nexus_x_inventory_v1')).length,111);for(const[key,value]of Object.entries(seeds))assert.equal(h.window.localStorage.getItem(key),value);h.api.bind();const prior=h.api.state.inventory;h.window.dispatchEvent(new h.window.StorageEvent('storage',{key:'nexus_x_inventory_v1',newValue:'[]'}));assert.equal(h.api.state.inventory,prior);}finally{h.close()}
});
test('Voice V2: bases de documentos y referencias locales independientes',async()=>{const h=harness({url});try{Object.defineProperty(h.document,'currentScript',{value:{src:url+'offline/core.js'},configurable:true});h.loadVendor('offline/assets.js');h.loadVendor('offline/core.js');assert.equal(typeof h.window.NexusOffline.createVoice,'function');await h.window.NexusOffline.saveReference({recordId:'NEXUS-X-0001',label:'prueba',embedding:Array(512).fill(0)});assert.equal((await h.api.getCachedDocs()).length,0);const names=(await h.window.indexedDB.databases()).map(x=>x.name);assert.ok(names.includes('nexus-visual-references-v1:voice-v2-test'));assert.ok(names.includes('NEXUS_X_DOCUMENTS_V2:voice-v2-test'));assert.ok(!names.includes('NEXUS_X_DOCUMENTS_V2'));assert.ok(!names.includes('nexus-visual-references-v1'));}finally{h.close()}});
